#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

#import socket module
from socket import *
import sys # In order to terminate the program
serverSocket = socket(AF_INET, SOCK_STREAM)
#Prepare a sever socket

#设置端口号9000
serverPort = 9000  # 端口号
serverSocket = socket(AF_INET,SOCK_STREAM)
serverSocket.bind(('',serverPort)) # IP为本地 localhost
serverSocket.listen(1)
#Fill in end
while True:
    #Establish the connection
    print('Ready to serve...')
    connectionSocket, addr =serverSocket.accept() #Fill in start #Fill in end
    try:
        message = connectionSocket.recv(1024)#Fill in start #Fill in end
        filename = message.split()[1]
        f = open(filename[1:], encoding='utf-8')
        outputdata =f.read() #Fill in start #Fill in end
        #Send one HTTP header line into socket
        #Fill in start
        header = 'HTTP/1.1 200 OK\nConnection: close\nContent-Type: text/html\nContent-Length: %d\n\n' % (len(outputdata))    
        connectionSocket.send(header.encode())
        #Fill in end
        
        #Send the content of the requested file to the client
        for i in range(0, len(outputdata)):
            connectionSocket.send(outputdata[i].encode())
        connectionSocket.close()
    except IOError:
        #Send response message for file not found
        #Fill in start
        header = 'HTTP/1.1 404 File not found\nConnection: close\nContent-Type: text/html;charset=utf-8\nContent-Length: 10\n\n'
        connectionSocket.send(header.encode())
        #Fill in end
        #Close client socket
        #Fill in start
        connectionSocket.close()
        #Fill in end
serverSocket.close()
sys.exit()#Terminate the program after sending the corresponding data

